### PR TITLE
Update to asciidoctor-diagram 2.0.5

### PR DESCRIPTION
**Pull request by pepijnve**

### CODE REVIEW

**Comment by pepijnve** [comment]
@robertpanzer I've tried to fix the unit tests a bit. They don't work with asciidoctorj 1.5.8 yet I'm afraid. The necessary bits of information are simply not getting passed on to the extension. If you really want to pin down where the images and cache files get written in the tests it would be better to set the `imagesoutdir` and `diagram-cachedir` attributes.

**Comment by robertpanzer** [comment]
@pepijnve Sorry, I completely forgot to push the 2.0.4 release.
I just did that, and of course (sorry!) it results in a merge conflict.
Could you please resolve that once you find some time?

And thank you so much for doing this pull request and all your great work on asciidoctor-diagram!

**Comment by pepijnve** [comment]
Conflicts resolved.

**Comment by robertpanzer** [comment]
Awesome, thank you!

**Pull request merged**
